  - name: 'Run Test Suite (:kubernetes: 1.8.2)'
    command: bin/ci
    agents:
      queue: minikube-v1.8.2
  - name: 'Run Test Suite (:kubernetes: 1.7.9)'
    command: bin/ci
    agents:
      queue: minikube-v1.7.9

